### ISSUE TITLE
[Feature Request]: Reb. and Inv. vs Occ. & Reb. and Occ. vs Inv.

### ISSUE THREAD

**Issue by simonmeulenbeek** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#230]
### Related problem

I'd like to be allied to the Invaders.

### Proposed feature

I play with Antistasi Ultimate with WW2 factions, and the current available gamemodes don't really make sense in that context. 
As an example, a rebel faction fighting the nazi occupation would probably welcome outside help from the invaders, instead of fighting them too.

Therefore I think it would be a great addition if there would either be more gamemodes, or some other way to set which factions are friendly.

Personally I'd be interested in seeing:
* Rebels and Occupiers VS Invaders
* Rebels and Invaders VS Occupiers

I do realize that Rebels being allied to Occupiers could probably break a lot gameplay/balance wise. But I think it would still be a great addition, and probably a lot of fun for roleplay.

**Comment by stutpip123** [comment]
making either faction friendly to players is not possible without breaking the regular mode

**Comment by Silence-112** [comment]
Reb and Occ would be pointless regardless of intentions as you'd likely win without even having to lift a finger.

Reb and Inv is also equally pointless because of the invaders intentions. They are not just an occupier but red, they also ACTIVELY try to kill the population - something you as a rebel force would not want to be associated with... After all, why would cities join you when you literally ally with the same people who kill them?
