### ISSUE TITLE
[Change Request]: requirments for unlocking vehicles should be a tiny bit lower

### ISSUE THREAD

**Issue by wersal454** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#257]
### Is the requested change related to a problem?

Currently unlock progression is a bit slow, at level 4 you can't buy anything from blackmarket even though you have 1 airbase and military base

### Describe the solution you'd like.

lower requirements just a bit(maybe more). For example make so unarmed cars unlock at 2 outpost + war lever "something"+ 1 factory

**Comment by Silence-112** [comment]
The only categories that should require war level are statics since they're a big part of progression, none of the other types should require WL

There is no good way to do it since all maps are different which is why we have the param to disable the requirements

Perhaps there should be a war level mercy rule that unlocks a category after a certain WL regardless of what zones you already have

**Comment by wersal454** [comment]
> Perhaps there should be a war level mercy rule that unlocks a category after a certain WL regardless of what zones you already have

That one, I like. Something like at war level 4 you unlock unarmed and armed cars? and at 5 boats

**Comment by stutpip123** [comment]
needing resources and factories in current quantities for many of the types is excessive. needing 3 res and 3 facs for basic armed cars, thats like war level 5/6

**Comment by Silence-112** [comment]
We should probably have a proper discussion and go through each ones requirements then

**Comment by Silence-112** [comment]
Done in #264
