### ISSUE TITLE
[Feature Request]: Shortcut action to send AI back to base aka evacuate

### ISSUE THREAD

**Issue by Araz0** [Antistasi-Ultimate-Community/A3-Antistasi-Ultimate#297]
### Related problem

when in a fight, and i want to safely send something back to the base via AI, its very hard to do everything needed; select the AI, open the map, zoom out, move to where HQ is, and then zoom in, and them click somewhere and hope the AI will do that.

### Proposed feature

Provide an option, best via action menu, that i can select an AI, and click it and it will ignore everything else and everything that is happening and it will go to a safe spot at the base. 
this way i can evacuate anything quickly from any fight, without the risk of me dying because i was looking at the map. 
i should be able to just radio a command to the AI and it will take care of how and where to go back.

**Comment by Silence-112** [comment]
The reason we generally don't let the AI do much themselves is because they're awful at doing it properly/in the way we want to

I feel this could cause more issues if people use it and the AI decide to run right into a roadblock or outpost on their way back effectively removing any benefit of the feature

**Comment by Silence-112** [comment]
Going to close this issue. If someone wants to do this, can be re-opened
